### ISSUE TITLE
the commands should return stuff to the web

### ISSUE THREAD

**Issue by KylomaskGamer** [BlauToad/webcommands#1]
say that i am making a fighting game with http requests
i want to know when there is no monsters in the arena
unfortunately, it returns nothing (for the browser side)
can it return stuff such as /list or /locate or smth like that

**Comment by BlauToad** [comment]
New update released. I hope this gives you everything you need. You can now send the command for example `localhost/get?"/list"`. This will return the chat message that would be displayed and a unformated text.
